# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Run Tests Backend

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yml'
  pull_request:
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json

    - name: Install Dependencies
      run: |
        cd backend
        npm ci

    - name: Run Tests
      run: |
        cd backend
        npm run test:ci

    - name: Jest Coverage Comment
      uses: MishaKav/jest-coverage-comment@main
      with:
        coverage-summary-path: ./backend/coverage/coverage-summary.json
        title: Backend Test Coverage
        summary-title: Summary
        badge-title: Coverage
        hide-comment: false
        create-new-comment: false
        hide-summary: false
        coverage-title: See all coverage details
        coverage-path: ./coverage.txt
      
